// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: historyquiz/quiz/v1/quiz_service.proto

package quizv1

import (
	v1 "github.com/history-quiz/historyquiz/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Ordinal       int32                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP(), []int{0}
}

func (x *Choice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Choice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Choice) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Choices       []*Choice              `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"` // 将来の拡張用（初期は空でもよい）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Question) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *Question) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type GetQuestionRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// 連続出題で直前の問題を避けたい場合に使う（将来拡張）。
	PreviousQuestionId string `protobuf:"bytes,2,opt,name=previous_question_id,json=previousQuestionId,proto3" json:"previous_question_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuestionRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetQuestionRequest) GetPreviousQuestionId() string {
	if x != nil {
		return x.PreviousQuestionId
	}
	return ""
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Question      *Question              `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuestionResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type SubmitAnswerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Context          *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	QuestionId       string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedChoiceId string                 `protobuf:"bytes,3,opt,name=selected_choice_id,json=selectedChoiceId,proto3" json:"selected_choice_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAnswerRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetSelectedChoiceId() string {
	if x != nil {
		return x.SelectedChoiceId
	}
	return ""
}

type SubmitAnswerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	IsCorrect       bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	CorrectChoiceId string                 `protobuf:"bytes,3,opt,name=correct_choice_id,json=correctChoiceId,proto3" json:"correct_choice_id,omitempty"`
	AttemptId       string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_quiz_v1_quiz_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAnswerResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitAnswerResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *SubmitAnswerResponse) GetCorrectChoiceId() string {
	if x != nil {
		return x.CorrectChoiceId
	}
	return ""
}

func (x *SubmitAnswerResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

var File_historyquiz_quiz_v1_quiz_service_proto protoreflect.FileDescriptor

const file_historyquiz_quiz_v1_quiz_service_proto_rawDesc = "" +
	"\n" +
	"&historyquiz/quiz/v1/quiz_service.proto\x12\x13historyquiz.quiz.v1\x1a\"historyquiz/common/v1/common.proto\"H\n" +
	"\x06Choice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x05R\aordinal\"\x8b\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x125\n" +
	"\achoices\x18\x03 \x03(\v2\x1b.historyquiz.quiz.v1.ChoiceR\achoices\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"\x87\x01\n" +
	"\x12GetQuestionRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x120\n" +
	"\x14previous_question_id\x18\x02 \x01(\tR\x12previousQuestionId\"\x91\x01\n" +
	"\x13GetQuestionResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x129\n" +
	"\bquestion\x18\x02 \x01(\v2\x1d.historyquiz.quiz.v1.QuestionR\bquestion\"\xa5\x01\n" +
	"\x13SubmitAnswerRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12,\n" +
	"\x12selected_choice_id\x18\x03 \x01(\tR\x10selectedChoiceId\"\xc1\x01\n" +
	"\x14SubmitAnswerResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x12*\n" +
	"\x11correct_choice_id\x18\x03 \x01(\tR\x0fcorrectChoiceId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId2\xd4\x01\n" +
	"\vQuizService\x12`\n" +
	"\vGetQuestion\x12'.historyquiz.quiz.v1.GetQuestionRequest\x1a(.historyquiz.quiz.v1.GetQuestionResponse\x12c\n" +
	"\fSubmitAnswer\x12(.historyquiz.quiz.v1.SubmitAnswerRequest\x1a).historyquiz.quiz.v1.SubmitAnswerResponseB:Z8github.com/history-quiz/historyquiz/proto/quiz/v1;quizv1b\x06proto3"

var (
	file_historyquiz_quiz_v1_quiz_service_proto_rawDescOnce sync.Once
	file_historyquiz_quiz_v1_quiz_service_proto_rawDescData []byte
)

func file_historyquiz_quiz_v1_quiz_service_proto_rawDescGZIP() []byte {
	file_historyquiz_quiz_v1_quiz_service_proto_rawDescOnce.Do(func() {
		file_historyquiz_quiz_v1_quiz_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historyquiz_quiz_v1_quiz_service_proto_rawDesc), len(file_historyquiz_quiz_v1_quiz_service_proto_rawDesc)))
	})
	return file_historyquiz_quiz_v1_quiz_service_proto_rawDescData
}

var file_historyquiz_quiz_v1_quiz_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_historyquiz_quiz_v1_quiz_service_proto_goTypes = []any{
	(*Choice)(nil),               // 0: historyquiz.quiz.v1.Choice
	(*Question)(nil),             // 1: historyquiz.quiz.v1.Question
	(*GetQuestionRequest)(nil),   // 2: historyquiz.quiz.v1.GetQuestionRequest
	(*GetQuestionResponse)(nil),  // 3: historyquiz.quiz.v1.GetQuestionResponse
	(*SubmitAnswerRequest)(nil),  // 4: historyquiz.quiz.v1.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil), // 5: historyquiz.quiz.v1.SubmitAnswerResponse
	(*v1.RequestContext)(nil),    // 6: historyquiz.common.v1.RequestContext
}
var file_historyquiz_quiz_v1_quiz_service_proto_depIdxs = []int32{
	0, // 0: historyquiz.quiz.v1.Question.choices:type_name -> historyquiz.quiz.v1.Choice
	6, // 1: historyquiz.quiz.v1.GetQuestionRequest.context:type_name -> historyquiz.common.v1.RequestContext
	6, // 2: historyquiz.quiz.v1.GetQuestionResponse.context:type_name -> historyquiz.common.v1.RequestContext
	1, // 3: historyquiz.quiz.v1.GetQuestionResponse.question:type_name -> historyquiz.quiz.v1.Question
	6, // 4: historyquiz.quiz.v1.SubmitAnswerRequest.context:type_name -> historyquiz.common.v1.RequestContext
	6, // 5: historyquiz.quiz.v1.SubmitAnswerResponse.context:type_name -> historyquiz.common.v1.RequestContext
	2, // 6: historyquiz.quiz.v1.QuizService.GetQuestion:input_type -> historyquiz.quiz.v1.GetQuestionRequest
	4, // 7: historyquiz.quiz.v1.QuizService.SubmitAnswer:input_type -> historyquiz.quiz.v1.SubmitAnswerRequest
	3, // 8: historyquiz.quiz.v1.QuizService.GetQuestion:output_type -> historyquiz.quiz.v1.GetQuestionResponse
	5, // 9: historyquiz.quiz.v1.QuizService.SubmitAnswer:output_type -> historyquiz.quiz.v1.SubmitAnswerResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_historyquiz_quiz_v1_quiz_service_proto_init() }
func file_historyquiz_quiz_v1_quiz_service_proto_init() {
	if File_historyquiz_quiz_v1_quiz_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historyquiz_quiz_v1_quiz_service_proto_rawDesc), len(file_historyquiz_quiz_v1_quiz_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_historyquiz_quiz_v1_quiz_service_proto_goTypes,
		DependencyIndexes: file_historyquiz_quiz_v1_quiz_service_proto_depIdxs,
		MessageInfos:      file_historyquiz_quiz_v1_quiz_service_proto_msgTypes,
	}.Build()
	File_historyquiz_quiz_v1_quiz_service_proto = out.File
	file_historyquiz_quiz_v1_quiz_service_proto_goTypes = nil
	file_historyquiz_quiz_v1_quiz_service_proto_depIdxs = nil
}
