// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: historyquiz/question/v1/question_service.proto

package questionv1

import (
	v1 "github.com/history-quiz/historyquiz/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339 文字列（言語間互換を優先）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionSummary) Reset() {
	*x = QuestionSummary{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionSummary) ProtoMessage() {}

func (x *QuestionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionSummary.ProtoReflect.Descriptor instead.
func (*QuestionSummary) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionSummary) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *QuestionSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type QuestionDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt          string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Choices         []*Choice              `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	CorrectChoiceId string                 `protobuf:"bytes,4,opt,name=correct_choice_id,json=correctChoiceId,proto3" json:"correct_choice_id,omitempty"`
	Explanation     string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuestionDetail) Reset() {
	*x = QuestionDetail{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDetail) ProtoMessage() {}

func (x *QuestionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDetail.ProtoReflect.Descriptor instead.
func (*QuestionDetail) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionDetail) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *QuestionDetail) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *QuestionDetail) GetCorrectChoiceId() string {
	if x != nil {
		return x.CorrectChoiceId
	}
	return ""
}

func (x *QuestionDetail) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *QuestionDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Ordinal       int32                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{2}
}

func (x *Choice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Choice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Choice) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

// 作問入力（作成/更新で共通）。
// NOTE: choices は常に4件であることをバックエンドで検証する。
type QuestionDraft struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prompt         string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Choices        []string               `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`                                      // 期待: 4件
	CorrectOrdinal int32                  `protobuf:"varint,3,opt,name=correct_ordinal,json=correctOrdinal,proto3" json:"correct_ordinal,omitempty"` // 期待: 0..3
	Explanation    string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuestionDraft) Reset() {
	*x = QuestionDraft{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDraft) ProtoMessage() {}

func (x *QuestionDraft) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDraft.ProtoReflect.Descriptor instead.
func (*QuestionDraft) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{3}
}

func (x *QuestionDraft) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *QuestionDraft) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *QuestionDraft) GetCorrectOrdinal() int32 {
	if x != nil {
		return x.CorrectOrdinal
	}
	return 0
}

func (x *QuestionDraft) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Draft         *QuestionDraft         `protobuf:"bytes,2,opt,name=draft,proto3" json:"draft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateQuestionRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateQuestionRequest) GetDraft() *QuestionDraft {
	if x != nil {
		return x.Draft
	}
	return nil
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Question      *QuestionDetail        `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQuestionResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateQuestionResponse) GetQuestion() *QuestionDetail {
	if x != nil {
		return x.Question
	}
	return nil
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Draft         *QuestionDraft         `protobuf:"bytes,3,opt,name=draft,proto3" json:"draft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateQuestionRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDraft() *QuestionDraft {
	if x != nil {
		return x.Draft
	}
	return nil
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Question      *QuestionDetail        `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateQuestionResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateQuestionResponse) GetQuestion() *QuestionDetail {
	if x != nil {
		return x.Question
	}
	return nil
}

type GetMyQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyQuestionRequest) Reset() {
	*x = GetMyQuestionRequest{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyQuestionRequest) ProtoMessage() {}

func (x *GetMyQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetMyQuestionRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetMyQuestionRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetMyQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type GetMyQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Question      *QuestionDetail        `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyQuestionResponse) Reset() {
	*x = GetMyQuestionResponse{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyQuestionResponse) ProtoMessage() {}

func (x *GetMyQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetMyQuestionResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetMyQuestionResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetMyQuestionResponse) GetQuestion() *QuestionDetail {
	if x != nil {
		return x.Question
	}
	return nil
}

type ListMyQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyQuestionsRequest) Reset() {
	*x = ListMyQuestionsRequest{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyQuestionsRequest) ProtoMessage() {}

func (x *ListMyQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListMyQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListMyQuestionsRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListMyQuestionsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMyQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Questions     []*QuestionSummary     `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyQuestionsResponse) Reset() {
	*x = ListMyQuestionsResponse{}
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyQuestionsResponse) ProtoMessage() {}

func (x *ListMyQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_question_v1_question_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListMyQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_question_v1_question_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyQuestionsResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListMyQuestionsResponse) GetQuestions() []*QuestionSummary {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *ListMyQuestionsResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_historyquiz_question_v1_question_service_proto protoreflect.FileDescriptor

const file_historyquiz_question_v1_question_service_proto_rawDesc = "" +
	"\n" +
	".historyquiz/question/v1/question_service.proto\x12\x17historyquiz.question.v1\x1a\"historyquiz/common/v1/common.proto\"X\n" +
	"\x0fQuestionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"\xe0\x01\n" +
	"\x0eQuestionDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x129\n" +
	"\achoices\x18\x03 \x03(\v2\x1f.historyquiz.question.v1.ChoiceR\achoices\x12*\n" +
	"\x11correct_choice_id\x18\x04 \x01(\tR\x0fcorrectChoiceId\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"H\n" +
	"\x06Choice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x05R\aordinal\"\x8c\x01\n" +
	"\rQuestionDraft\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x18\n" +
	"\achoices\x18\x02 \x03(\tR\achoices\x12'\n" +
	"\x0fcorrect_ordinal\x18\x03 \x01(\x05R\x0ecorrectOrdinal\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"\x96\x01\n" +
	"\x15CreateQuestionRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12<\n" +
	"\x05draft\x18\x02 \x01(\v2&.historyquiz.question.v1.QuestionDraftR\x05draft\"\x9e\x01\n" +
	"\x16CreateQuestionResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12C\n" +
	"\bquestion\x18\x02 \x01(\v2'.historyquiz.question.v1.QuestionDetailR\bquestion\"\xb7\x01\n" +
	"\x15UpdateQuestionRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12<\n" +
	"\x05draft\x18\x03 \x01(\v2&.historyquiz.question.v1.QuestionDraftR\x05draft\"\x9e\x01\n" +
	"\x16UpdateQuestionResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12C\n" +
	"\bquestion\x18\x02 \x01(\v2'.historyquiz.question.v1.QuestionDetailR\bquestion\"x\n" +
	"\x14GetMyQuestionRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\"\x9d\x01\n" +
	"\x15GetMyQuestionResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12C\n" +
	"\bquestion\x18\x02 \x01(\v2'.historyquiz.question.v1.QuestionDetailR\bquestion\"\x9c\x01\n" +
	"\x16ListMyQuestionsRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.historyquiz.common.v1.PaginationR\n" +
	"pagination\"\xe0\x01\n" +
	"\x17ListMyQuestionsResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12F\n" +
	"\tquestions\x18\x02 \x03(\v2(.historyquiz.question.v1.QuestionSummaryR\tquestions\x12<\n" +
	"\tpage_info\x18\x03 \x01(\v2\x1f.historyquiz.common.v1.PageInfoR\bpageInfo2\xdd\x03\n" +
	"\x0fQuestionService\x12q\n" +
	"\x0eCreateQuestion\x12..historyquiz.question.v1.CreateQuestionRequest\x1a/.historyquiz.question.v1.CreateQuestionResponse\x12q\n" +
	"\x0eUpdateQuestion\x12..historyquiz.question.v1.UpdateQuestionRequest\x1a/.historyquiz.question.v1.UpdateQuestionResponse\x12n\n" +
	"\rGetMyQuestion\x12-.historyquiz.question.v1.GetMyQuestionRequest\x1a..historyquiz.question.v1.GetMyQuestionResponse\x12t\n" +
	"\x0fListMyQuestions\x12/.historyquiz.question.v1.ListMyQuestionsRequest\x1a0.historyquiz.question.v1.ListMyQuestionsResponseBBZ@github.com/history-quiz/historyquiz/proto/question/v1;questionv1b\x06proto3"

var (
	file_historyquiz_question_v1_question_service_proto_rawDescOnce sync.Once
	file_historyquiz_question_v1_question_service_proto_rawDescData []byte
)

func file_historyquiz_question_v1_question_service_proto_rawDescGZIP() []byte {
	file_historyquiz_question_v1_question_service_proto_rawDescOnce.Do(func() {
		file_historyquiz_question_v1_question_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historyquiz_question_v1_question_service_proto_rawDesc), len(file_historyquiz_question_v1_question_service_proto_rawDesc)))
	})
	return file_historyquiz_question_v1_question_service_proto_rawDescData
}

var file_historyquiz_question_v1_question_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_historyquiz_question_v1_question_service_proto_goTypes = []any{
	(*QuestionSummary)(nil),         // 0: historyquiz.question.v1.QuestionSummary
	(*QuestionDetail)(nil),          // 1: historyquiz.question.v1.QuestionDetail
	(*Choice)(nil),                  // 2: historyquiz.question.v1.Choice
	(*QuestionDraft)(nil),           // 3: historyquiz.question.v1.QuestionDraft
	(*CreateQuestionRequest)(nil),   // 4: historyquiz.question.v1.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),  // 5: historyquiz.question.v1.CreateQuestionResponse
	(*UpdateQuestionRequest)(nil),   // 6: historyquiz.question.v1.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),  // 7: historyquiz.question.v1.UpdateQuestionResponse
	(*GetMyQuestionRequest)(nil),    // 8: historyquiz.question.v1.GetMyQuestionRequest
	(*GetMyQuestionResponse)(nil),   // 9: historyquiz.question.v1.GetMyQuestionResponse
	(*ListMyQuestionsRequest)(nil),  // 10: historyquiz.question.v1.ListMyQuestionsRequest
	(*ListMyQuestionsResponse)(nil), // 11: historyquiz.question.v1.ListMyQuestionsResponse
	(*v1.RequestContext)(nil),       // 12: historyquiz.common.v1.RequestContext
	(*v1.Pagination)(nil),           // 13: historyquiz.common.v1.Pagination
	(*v1.PageInfo)(nil),             // 14: historyquiz.common.v1.PageInfo
}
var file_historyquiz_question_v1_question_service_proto_depIdxs = []int32{
	2,  // 0: historyquiz.question.v1.QuestionDetail.choices:type_name -> historyquiz.question.v1.Choice
	12, // 1: historyquiz.question.v1.CreateQuestionRequest.context:type_name -> historyquiz.common.v1.RequestContext
	3,  // 2: historyquiz.question.v1.CreateQuestionRequest.draft:type_name -> historyquiz.question.v1.QuestionDraft
	12, // 3: historyquiz.question.v1.CreateQuestionResponse.context:type_name -> historyquiz.common.v1.RequestContext
	1,  // 4: historyquiz.question.v1.CreateQuestionResponse.question:type_name -> historyquiz.question.v1.QuestionDetail
	12, // 5: historyquiz.question.v1.UpdateQuestionRequest.context:type_name -> historyquiz.common.v1.RequestContext
	3,  // 6: historyquiz.question.v1.UpdateQuestionRequest.draft:type_name -> historyquiz.question.v1.QuestionDraft
	12, // 7: historyquiz.question.v1.UpdateQuestionResponse.context:type_name -> historyquiz.common.v1.RequestContext
	1,  // 8: historyquiz.question.v1.UpdateQuestionResponse.question:type_name -> historyquiz.question.v1.QuestionDetail
	12, // 9: historyquiz.question.v1.GetMyQuestionRequest.context:type_name -> historyquiz.common.v1.RequestContext
	12, // 10: historyquiz.question.v1.GetMyQuestionResponse.context:type_name -> historyquiz.common.v1.RequestContext
	1,  // 11: historyquiz.question.v1.GetMyQuestionResponse.question:type_name -> historyquiz.question.v1.QuestionDetail
	12, // 12: historyquiz.question.v1.ListMyQuestionsRequest.context:type_name -> historyquiz.common.v1.RequestContext
	13, // 13: historyquiz.question.v1.ListMyQuestionsRequest.pagination:type_name -> historyquiz.common.v1.Pagination
	12, // 14: historyquiz.question.v1.ListMyQuestionsResponse.context:type_name -> historyquiz.common.v1.RequestContext
	0,  // 15: historyquiz.question.v1.ListMyQuestionsResponse.questions:type_name -> historyquiz.question.v1.QuestionSummary
	14, // 16: historyquiz.question.v1.ListMyQuestionsResponse.page_info:type_name -> historyquiz.common.v1.PageInfo
	4,  // 17: historyquiz.question.v1.QuestionService.CreateQuestion:input_type -> historyquiz.question.v1.CreateQuestionRequest
	6,  // 18: historyquiz.question.v1.QuestionService.UpdateQuestion:input_type -> historyquiz.question.v1.UpdateQuestionRequest
	8,  // 19: historyquiz.question.v1.QuestionService.GetMyQuestion:input_type -> historyquiz.question.v1.GetMyQuestionRequest
	10, // 20: historyquiz.question.v1.QuestionService.ListMyQuestions:input_type -> historyquiz.question.v1.ListMyQuestionsRequest
	5,  // 21: historyquiz.question.v1.QuestionService.CreateQuestion:output_type -> historyquiz.question.v1.CreateQuestionResponse
	7,  // 22: historyquiz.question.v1.QuestionService.UpdateQuestion:output_type -> historyquiz.question.v1.UpdateQuestionResponse
	9,  // 23: historyquiz.question.v1.QuestionService.GetMyQuestion:output_type -> historyquiz.question.v1.GetMyQuestionResponse
	11, // 24: historyquiz.question.v1.QuestionService.ListMyQuestions:output_type -> historyquiz.question.v1.ListMyQuestionsResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_historyquiz_question_v1_question_service_proto_init() }
func file_historyquiz_question_v1_question_service_proto_init() {
	if File_historyquiz_question_v1_question_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historyquiz_question_v1_question_service_proto_rawDesc), len(file_historyquiz_question_v1_question_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_historyquiz_question_v1_question_service_proto_goTypes,
		DependencyIndexes: file_historyquiz_question_v1_question_service_proto_depIdxs,
		MessageInfos:      file_historyquiz_question_v1_question_service_proto_msgTypes,
	}.Build()
	File_historyquiz_question_v1_question_service_proto = out.File
	file_historyquiz_question_v1_question_service_proto_goTypes = nil
	file_historyquiz_question_v1_question_service_proto_depIdxs = nil
}
