// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: historyquiz/user/v1/user_service.proto

package userv1

import (
	v1 "github.com/history-quiz/historyquiz/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attempt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId       string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	QuestionPrompt   string                 `protobuf:"bytes,3,opt,name=question_prompt,json=questionPrompt,proto3" json:"question_prompt,omitempty"`
	SelectedChoiceId string                 `protobuf:"bytes,4,opt,name=selected_choice_id,json=selectedChoiceId,proto3" json:"selected_choice_id,omitempty"`
	IsCorrect        bool                   `protobuf:"varint,5,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	AnsweredAt       string                 `protobuf:"bytes,6,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"` // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_historyquiz_user_v1_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *Attempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attempt) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Attempt) GetQuestionPrompt() string {
	if x != nil {
		return x.QuestionPrompt
	}
	return ""
}

func (x *Attempt) GetSelectedChoiceId() string {
	if x != nil {
		return x.SelectedChoiceId
	}
	return ""
}

func (x *Attempt) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *Attempt) GetAnsweredAt() string {
	if x != nil {
		return x.AnsweredAt
	}
	return ""
}

type Stats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalAttempts   int64                  `protobuf:"varint,1,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	CorrectAttempts int64                  `protobuf:"varint,2,opt,name=correct_attempts,json=correctAttempts,proto3" json:"correct_attempts,omitempty"`
	Accuracy        float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"` // 0.0..1.0
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_historyquiz_user_v1_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *Stats) GetTotalAttempts() int64 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *Stats) GetCorrectAttempts() int64 {
	if x != nil {
		return x.CorrectAttempts
	}
	return 0
}

func (x *Stats) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type ListMyAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyAttemptsRequest) Reset() {
	*x = ListMyAttemptsRequest{}
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyAttemptsRequest) ProtoMessage() {}

func (x *ListMyAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyAttemptsRequest.ProtoReflect.Descriptor instead.
func (*ListMyAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_user_v1_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListMyAttemptsRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListMyAttemptsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMyAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Attempts      []*Attempt             `protobuf:"bytes,2,rep,name=attempts,proto3" json:"attempts,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyAttemptsResponse) Reset() {
	*x = ListMyAttemptsResponse{}
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyAttemptsResponse) ProtoMessage() {}

func (x *ListMyAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyAttemptsResponse.ProtoReflect.Descriptor instead.
func (*ListMyAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_user_v1_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListMyAttemptsResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListMyAttemptsResponse) GetAttempts() []*Attempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *ListMyAttemptsResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetMyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyStatsRequest) Reset() {
	*x = GetMyStatsRequest{}
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyStatsRequest) ProtoMessage() {}

func (x *GetMyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMyStatsRequest) Descriptor() ([]byte, []int) {
	return file_historyquiz_user_v1_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyStatsRequest) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetMyStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.RequestContext     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Stats         *Stats                 `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyStatsResponse) Reset() {
	*x = GetMyStatsResponse{}
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyStatsResponse) ProtoMessage() {}

func (x *GetMyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historyquiz_user_v1_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMyStatsResponse) Descriptor() ([]byte, []int) {
	return file_historyquiz_user_v1_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyStatsResponse) GetContext() *v1.RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetMyStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_historyquiz_user_v1_user_service_proto protoreflect.FileDescriptor

const file_historyquiz_user_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"&historyquiz/user/v1/user_service.proto\x12\x13historyquiz.user.v1\x1a\"historyquiz/common/v1/common.proto\"\xd1\x01\n" +
	"\aAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12'\n" +
	"\x0fquestion_prompt\x18\x03 \x01(\tR\x0equestionPrompt\x12,\n" +
	"\x12selected_choice_id\x18\x04 \x01(\tR\x10selectedChoiceId\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x05 \x01(\bR\tisCorrect\x12\x1f\n" +
	"\vanswered_at\x18\x06 \x01(\tR\n" +
	"answeredAt\"u\n" +
	"\x05Stats\x12%\n" +
	"\x0etotal_attempts\x18\x01 \x01(\x03R\rtotalAttempts\x12)\n" +
	"\x10correct_attempts\x18\x02 \x01(\x03R\x0fcorrectAttempts\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\"\x9b\x01\n" +
	"\x15ListMyAttemptsRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.historyquiz.common.v1.PaginationR\n" +
	"pagination\"\xd1\x01\n" +
	"\x16ListMyAttemptsResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x128\n" +
	"\battempts\x18\x02 \x03(\v2\x1c.historyquiz.user.v1.AttemptR\battempts\x12<\n" +
	"\tpage_info\x18\x03 \x01(\v2\x1f.historyquiz.common.v1.PageInfoR\bpageInfo\"T\n" +
	"\x11GetMyStatsRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\"\x87\x01\n" +
	"\x12GetMyStatsResponse\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.historyquiz.common.v1.RequestContextR\acontext\x120\n" +
	"\x05stats\x18\x02 \x01(\v2\x1a.historyquiz.user.v1.StatsR\x05stats2\xd7\x01\n" +
	"\vUserService\x12i\n" +
	"\x0eListMyAttempts\x12*.historyquiz.user.v1.ListMyAttemptsRequest\x1a+.historyquiz.user.v1.ListMyAttemptsResponse\x12]\n" +
	"\n" +
	"GetMyStats\x12&.historyquiz.user.v1.GetMyStatsRequest\x1a'.historyquiz.user.v1.GetMyStatsResponseB:Z8github.com/history-quiz/historyquiz/proto/user/v1;userv1b\x06proto3"

var (
	file_historyquiz_user_v1_user_service_proto_rawDescOnce sync.Once
	file_historyquiz_user_v1_user_service_proto_rawDescData []byte
)

func file_historyquiz_user_v1_user_service_proto_rawDescGZIP() []byte {
	file_historyquiz_user_v1_user_service_proto_rawDescOnce.Do(func() {
		file_historyquiz_user_v1_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historyquiz_user_v1_user_service_proto_rawDesc), len(file_historyquiz_user_v1_user_service_proto_rawDesc)))
	})
	return file_historyquiz_user_v1_user_service_proto_rawDescData
}

var file_historyquiz_user_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_historyquiz_user_v1_user_service_proto_goTypes = []any{
	(*Attempt)(nil),                // 0: historyquiz.user.v1.Attempt
	(*Stats)(nil),                  // 1: historyquiz.user.v1.Stats
	(*ListMyAttemptsRequest)(nil),  // 2: historyquiz.user.v1.ListMyAttemptsRequest
	(*ListMyAttemptsResponse)(nil), // 3: historyquiz.user.v1.ListMyAttemptsResponse
	(*GetMyStatsRequest)(nil),      // 4: historyquiz.user.v1.GetMyStatsRequest
	(*GetMyStatsResponse)(nil),     // 5: historyquiz.user.v1.GetMyStatsResponse
	(*v1.RequestContext)(nil),      // 6: historyquiz.common.v1.RequestContext
	(*v1.Pagination)(nil),          // 7: historyquiz.common.v1.Pagination
	(*v1.PageInfo)(nil),            // 8: historyquiz.common.v1.PageInfo
}
var file_historyquiz_user_v1_user_service_proto_depIdxs = []int32{
	6,  // 0: historyquiz.user.v1.ListMyAttemptsRequest.context:type_name -> historyquiz.common.v1.RequestContext
	7,  // 1: historyquiz.user.v1.ListMyAttemptsRequest.pagination:type_name -> historyquiz.common.v1.Pagination
	6,  // 2: historyquiz.user.v1.ListMyAttemptsResponse.context:type_name -> historyquiz.common.v1.RequestContext
	0,  // 3: historyquiz.user.v1.ListMyAttemptsResponse.attempts:type_name -> historyquiz.user.v1.Attempt
	8,  // 4: historyquiz.user.v1.ListMyAttemptsResponse.page_info:type_name -> historyquiz.common.v1.PageInfo
	6,  // 5: historyquiz.user.v1.GetMyStatsRequest.context:type_name -> historyquiz.common.v1.RequestContext
	6,  // 6: historyquiz.user.v1.GetMyStatsResponse.context:type_name -> historyquiz.common.v1.RequestContext
	1,  // 7: historyquiz.user.v1.GetMyStatsResponse.stats:type_name -> historyquiz.user.v1.Stats
	2,  // 8: historyquiz.user.v1.UserService.ListMyAttempts:input_type -> historyquiz.user.v1.ListMyAttemptsRequest
	4,  // 9: historyquiz.user.v1.UserService.GetMyStats:input_type -> historyquiz.user.v1.GetMyStatsRequest
	3,  // 10: historyquiz.user.v1.UserService.ListMyAttempts:output_type -> historyquiz.user.v1.ListMyAttemptsResponse
	5,  // 11: historyquiz.user.v1.UserService.GetMyStats:output_type -> historyquiz.user.v1.GetMyStatsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_historyquiz_user_v1_user_service_proto_init() }
func file_historyquiz_user_v1_user_service_proto_init() {
	if File_historyquiz_user_v1_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historyquiz_user_v1_user_service_proto_rawDesc), len(file_historyquiz_user_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_historyquiz_user_v1_user_service_proto_goTypes,
		DependencyIndexes: file_historyquiz_user_v1_user_service_proto_depIdxs,
		MessageInfos:      file_historyquiz_user_v1_user_service_proto_msgTypes,
	}.Build()
	File_historyquiz_user_v1_user_service_proto = out.File
	file_historyquiz_user_v1_user_service_proto_goTypes = nil
	file_historyquiz_user_v1_user_service_proto_depIdxs = nil
}
